//package it.unipd.testbase.gui;
//
//import it.unipd.testbase.eventdispatcher.EventDispatcher;
//import it.unipd.testbase.eventdispatcher.event.IEvent;
//import it.unipd.testbase.eventdispatcher.event.gui.UpdateGuiEvent;
//import it.unipd.testbase.helper.Log;
//
//import java.awt.FlowLayout;
//import java.util.ArrayList;
//import java.util.List;
//
//import javax.swing.text.DefaultCaret;
//
///**
// *
// * @author Fabio De Gaspari
// */
//public class BackupGui extends javax.swing.JFrame implements IGuiComponent {
//	protected static final String TAG = "it.unipd.testbase";
//	private List<CarWidget> cars = new ArrayList<CarWidget>();
//	private int curCar = -1;
//
//	private static final long serialVersionUID = 1L;
//	/**
//	 * Creates new form NewJFrame
//	 */
//	public BackupGui() {
//		initComponents();
//		DefaultCaret caret = (DefaultCaret)receivedMsgTxt.getCaret();
//		caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
//		setVisible(true);
//		register();
//	}
//
//	/**
//	 * This method is called from within the constructor to initialize the form.
//	 * WARNING: Do NOT modify this code. The content of this method is always
//	 * regenerated by the Form Editor.
//	 */
//	@SuppressWarnings("unchecked")
//	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//	private void initComponents() {
//
//		jPanel1 = new javax.swing.JPanel();
//		upperScrlPane = new javax.swing.JScrollPane();
//		jPanel2 = new javax.swing.JPanel();
//		jButton1 = new javax.swing.JButton();
//		jButton2 = new javax.swing.JButton();
//		jButton3 = new javax.swing.JButton();
//		jButton4 = new javax.swing.JButton();
//		lowerScrlPane = new javax.swing.JScrollPane();
//		receivedMsgTxt = new javax.swing.JTextArea();
//
//		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
//		jPanel1.setLayout(jPanel1Layout);
//		jPanel1Layout.setHorizontalGroup(
//				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//				.addComponent(upperScrlPane)
//				);
//		jPanel1Layout.setVerticalGroup(
//				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//				.addGroup(jPanel1Layout.createSequentialGroup()
//						.addComponent(upperScrlPane, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
//						.addGap(0, 0, Short.MAX_VALUE))
//				);
//		
//		//upperScrlPane.setLayout(new FlowLayout());
//
//		jButton1.setText("jButton1");
//
//		jButton2.setText("jButton2");
//
//		jButton3.setText("jButton3");
//
//		jButton4.setText("jButton4");
//
//		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
//		jPanel2.setLayout(jPanel2Layout);
//		jPanel2Layout.setHorizontalGroup(
//				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//				.addGroup(jPanel2Layout.createSequentialGroup()
//						.addComponent(jButton1)
//						.addGap(26, 26, 26)
//						.addComponent(jButton2)
//						.addGap(33, 33, 33)
//						.addComponent(jButton3)
//						.addGap(36, 36, 36)
//						.addComponent(jButton4)
//						.addGap(0, 313, Short.MAX_VALUE))
//				);
//		jPanel2Layout.setVerticalGroup(
//				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
//						.addGap(0, 12, Short.MAX_VALUE)
//						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//								.addComponent(jButton1)
//								.addComponent(jButton2)
//								.addComponent(jButton3)
//								.addComponent(jButton4)))
//				);
//
//		receivedMsgTxt.setColumns(20);
//		receivedMsgTxt.setRows(5);
//		lowerScrlPane.setViewportView(receivedMsgTxt);
//
//		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//		getContentPane().setLayout(layout);
//		layout.setHorizontalGroup(
//				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//				.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//				.addComponent(lowerScrlPane)
//				);
//		layout.setVerticalGroup(
//				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//				.addGroup(layout.createSequentialGroup()
//						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//						.addComponent(lowerScrlPane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
//				);
//
//		pack();
//	}// </editor-fold>//GEN-END:initComponents
//
//	// Variables declaration - do not modify//GEN-BEGIN:variables
//	private javax.swing.JButton jButton1;
//	private javax.swing.JButton jButton2;
//	private javax.swing.JButton jButton3;
//	private javax.swing.JButton jButton4;
//	private javax.swing.JPanel jPanel1;
//	private javax.swing.JPanel jPanel2;
//	private javax.swing.JScrollPane lowerScrlPane;
//	private javax.swing.JScrollPane upperScrlPane;
//	private javax.swing.JTextArea receivedMsgTxt;
//	// End of variables declaration//GEN-END:variables
//
//	@Override
//	public void handle(IEvent event) {
//		if(event instanceof UpdateGuiEvent)
//		{
//			UpdateGuiEvent ev = (UpdateGuiEvent) event;
//			switch(ev.type) {
//			case UpdateGuiEvent.GUI_UPDATE_NEW_MESSAGE:
//				Log.d(TAG, this.getClass().getSimpleName()+": Gui update message");
//				receivedMsgTxt.append("\n"+ev.obj.toString());
//				break;
//			case UpdateGuiEvent.GUI_UPDATE_CONT_WINDOW_START:
//				Log.d(TAG, this.getClass().getSimpleName()+": Contention window update message");
//				addCar((Integer[])ev.obj);
//				break;
//			case UpdateGuiEvent.GUI_UPDATE_MESSAGE_FORWARDED:
//				cars.get(curCar).setState(CarWidget.STATE_FORWARDED);
//				Log.d(TAG, this.getClass().getSimpleName()+": State forwarded update message");
//				break;
//			case UpdateGuiEvent.GUI_UPDATE_MESSAGE_NOT_FORWARDED:
//				cars.get(curCar).setState(CarWidget.STATE_DEAD);
//				Log.d(TAG, this.getClass().getSimpleName()+": State not forwarded update message");
//				break;
//			}
//		}
//	}
//
//	private void addCar(Integer[] vals) {
//		curCar++;
//		CarWidget cw = new CarWidget();
//		cw.setState(CarWidget.STATE_ACTIVE);
//		cw.setContentionWindow(vals[0], vals[1]);
//		cars.add(cw);
//		upperScrlPane.add(cw);
//		cw.setVisible(true);
//		upperScrlPane.revalidate();
//		upperScrlPane.repaint();
//	}
//
//	@Override
//	public void register() {
//		List<Class<? extends IEvent>> events = new ArrayList<Class<? extends IEvent>>();
//		events.add(UpdateGuiEvent.class);
//		EventDispatcher.getInstance().registerComponent(this, events);
//	}
//}
